sudo: false

language: node_js
node_js:
  - '6'

cache:
  directories:
    - node_modules

git:
  depth: 1

before_install:
  - npm install -g bower
  - npm install -g gulp-cli

script:
  - gulp build
